name: Modal Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  modal_deply:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install Modal
        run: pip install -r dev-requirements.txt -r modal/requirements.txt

      - name: Deploy job (wildcard for all files)
        run: |
          for file in $(find tools -type f -name 'modal.py'); do
            modal deploy $file
          done
        env: # SEE: https://modal.com/docs/guide/environment_variables#runtime-environment-variables
          MODAL_DEPLOY_TOKEN: ${{ secrets.MODAL_DEPLOY_TOKEN }}
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
          MODAL_ENVIRONMENT: chemistry
